#!/usr/bin/env python3
"""
fix_sacco_management.py

Auto-fix script for sacco_management ERPNext app.
- Fixes/creates DocType controllers
- Repairs missing utility functions
- Inserts Dashboard Charts safely
Compatible with ERPNext 15 / Frappe 15

Usage:
    bench --site sitename execute sacco_management.fix_sacco_management.run_all_fixes
    
Or directly:
    python fix_sacco_management.py
"""

import os
import sys
import frappe
from typing import List, Dict, Any


# Configuration
APP_NAME = "sacco_management"
APP_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), APP_NAME, "sacco", "doctype")
UTILS_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), APP_NAME, "sacco", "utils", "loan_utils.py")


def snake_to_camel(snake_str: str) -> str:
    """Convert snake_case to PascalCase"""
    return "".join(word.title() for word in snake_str.split("_"))


def get_doctype_folders() -> List[str]:
    """Get all doctype folders"""
    if not os.path.exists(APP_PATH):
        print(f"❌ App path not found: {APP_PATH}")
        return []
    
    folders = []
    for folder in os.listdir(APP_PATH):
        folder_path = os.path.join(APP_PATH, folder)
        if os.path.isdir(folder_path):
            folders.append(folder)
    
    return sorted(folders)


# -----------------------------
# 1. Fix DocType Controllers
# -----------------------------
def fix_controllers() -> Dict[str, List[str]]:
    """Fix or create all DocType controller files"""
    
    created = []
    fixed = []
    errors = []
    
    folders = get_doctype_folders()
    
    for folder in folders:
        try:
            folder_path = os.path.join(APP_PATH, folder)
            controller_file = os.path.join(folder_path, f"{folder}.py")
            init_file = os.path.join(folder_path, "__init__.py")
            class_name = snake_to_camel(folder)
            
            # Create controller content
            controller_content = f"""# Copyright (c) 2024, SACCO Developer and contributors
# For license information, see license.txt

import frappe
from frappe.model.document import Document


class {class_name}(Document):
\t\"\"\"{class_name} DocType Controller\"\"\"
\tpass
"""
            
            # Check if controller exists
            if not os.path.exists(controller_file):
                # Create new controller
                with open(controller_file, "w", encoding="utf-8") as f:
                    f.write(controller_content)
                created.append(folder)
                print(f"✅ Created: {folder}.py")
            else:
                # Check and fix existing controller
                with open(controller_file, "r", encoding="utf-8") as f:
                    existing = f.read()
                
                if f"class {class_name}(Document)" not in existing:
                    with open(controller_file, "w", encoding="utf-8") as f:
                        f.write(controller_content)
                    fixed.append(folder)
                    print(f"🔧 Fixed: {folder}.py")
            
            # Fix __init__.py
            init_content = f"""# Copyright (c) 2024, SACCO Developer and contributors
# For license information, see license.txt

from .{folder} import {class_name}

__all__ = ["{class_name}"]
"""
            
            with open(init_file, "w", encoding="utf-8") as f:
                f.write(init_content)
        
        except Exception as e:
            errors.append(f"{folder}: {str(e)}")
            print(f"❌ Error with {folder}: {str(e)}")
    
    result = {
        "created": created,
        "fixed": fixed,
        "errors": errors
    }
    
    print(f"\n{'='*60}")
    print(f"Controllers Created: {len(created)}")
    print(f"Controllers Fixed: {len(fixed)}")
    print(f"Errors: {len(errors)}")
    print(f"{'='*60}\n")
    
    return result


# -----------------------------
# 2. Repair Missing Utilities
# -----------------------------
def ensure_utility_functions() -> Dict[str, Any]:
    """Ensure all required utility functions exist"""
    
    result = {
        "added": [],
        "errors": []
    }
    
    # Required functions with their signatures
    required_functions = {
        "calculate_loan_summary": "def calculate_loan_summary(loan_id=None):\n    \"\"\"Calculate loan summary statistics\"\"\"\n    return {}\n",
        "get_loan_outstanding": "def get_loan_outstanding(loan_id):\n    \"\"\"Get outstanding loan amount\"\"\"\n    return 0\n",
        "process_loan_repayment": "def process_loan_repayment(loan_id, amount):\n    \"\"\"Process loan repayment\"\"\"\n    pass\n"
    }
    
    try:
        # Ensure directory exists
        os.makedirs(os.path.dirname(UTILS_FILE), exist_ok=True)
        
        # Check if file exists
        if os.path.exists(UTILS_FILE):
            with open(UTILS_FILE, "r", encoding="utf-8") as f:
                content = f.read()
        else:
            content = "# SACCO Loan Utilities\n# Auto-generated by fix_sacco_management.py\n\n"
        
        # Add missing functions
        for func_name, func_code in required_functions.items():
            if f"def {func_name}" not in content:
                content += f"\n{func_code}\n"
                result["added"].append(func_name)
                print(f"✅ Added: {func_name}()")
        
        # Write updated content
        with open(UTILS_FILE, "w", encoding="utf-8") as f:
            f.write(content)
        
        print(f"\n{'='*60}")
        print(f"Functions Added: {len(result['added'])}")
        print(f"{'='*60}\n")
    
    except Exception as e:
        error_msg = f"Error updating utils: {str(e)}"
        result["errors"].append(error_msg)
        print(f"❌ {error_msg}")
    
    return result


# -----------------------------
# 3. Fix Dashboard Charts
# -----------------------------
DASHBOARD_CHARTS = [
    {
        "chart_name": "System Performance Metrics",
        "chart_type": "Custom",
        "doctype": "Dashboard Chart",
        "document_type": "SACCO Member",
        "dynamic_filters_json": "[]",
        "filters_json": '[["SACCO Member","membership_status","=","Active",false]]',
        "group_by_type": "Count",
        "is_public": 1,
        "is_standard": 1,
        "module": "SACCO",
        "number_of_groups": 0,
        "timeseries": 1,
        "timespan": "Last Year",
        "time_interval": "Monthly",
        "value_based_on": "",
        "y_axis": [{"color": "green", "label": "New Members"}]
    },
    {
        "chart_name": "Member Growth",
        "chart_type": "Custom",
        "doctype": "Dashboard Chart",
        "document_type": "SACCO Member",
        "based_on": "creation",
        "filters_json": '[["SACCO Member","docstatus","=",1,false]]',
        "group_by_type": "Count",
        "is_public": 1,
        "is_standard": 1,
        "module": "SACCO",
        "timeseries": 1,
        "timespan": "Last Year",
        "time_interval": "Monthly"
    },
    {
        "chart_name": "Loan Disbursement Trend",
        "chart_type": "Custom",
        "doctype": "Dashboard Chart",
        "document_type": "Loan Application",
        "based_on": "disbursement_date",
        "value_based_on": "amount_approved",
        "filters_json": '[["Loan Application","status","=","Disbursed",false]]',
        "group_by_type": "Sum",
        "is_public": 1,
        "is_standard": 1,
        "module": "SACCO",
        "timeseries": 1,
        "timespan": "Last Year",
        "time_interval": "Monthly"
    },
    {
        "chart_name": "Savings Growth",
        "chart_type": "Custom",
        "doctype": "Dashboard Chart",
        "document_type": "Savings Account",
        "based_on": "creation",
        "value_based_on": "current_balance",
        "filters_json": '[["Savings Account","status","=","Active",false],["Savings Account","docstatus","=",1,false]]',
        "group_by_type": "Sum",
        "is_public": 1,
        "is_standard": 1,
        "module": "SACCO",
        "timeseries": 1,
        "timespan": "Last Year",
        "time_interval": "Monthly"
    },
    {
        "chart_name": "Share Capital Growth",
        "chart_type": "Custom",
        "doctype": "Dashboard Chart",
        "document_type": "Share Allocation",
        "based_on": "allocation_date",
        "value_based_on": "total_amount",
        "filters_json": '[["Share Allocation","status","=","Allocated",false],["Share Allocation","docstatus","=",1,false]]',
        "group_by_type": "Sum",
        "is_public": 1,
        "is_standard": 1,
        "module": "SACCO",
        "timeseries": 1,
        "timespan": "Last Year",
        "time_interval": "Monthly"
    }
]


def insert_dashboard_charts(site_name: str = None) -> Dict[str, Any]:
    """Safely insert dashboard charts"""
    
    result = {
        "inserted": [],
        "skipped": [],
        "errors": []
    }
    
    try:
        # Initialize Frappe if site provided
        if site_name:
            frappe.init(site=site_name)
            frappe.connect()
            print(f"✅ Connected to site: {site_name}")
        else:
            # Try to use current site
            site_name = getattr(frappe.local, "site", None)
            if not site_name:
                print("⚠️  No site specified. Run with: bench --site sitename execute ...")
                return result
        
        for chart in DASHBOARD_CHARTS:
            try:
                # Check if exists
                existing = frappe.db.exists("Dashboard Chart", {"chart_name": chart["chart_name"]})
                
                if existing:
                    result["skipped"].append(chart["chart_name"])
                    print(f"⏭️  Exists: {chart['chart_name']}")
                    continue
                
                # Insert chart (without name field to avoid KeyError)
                doc = frappe.get_doc(chart)
                doc.insert(ignore_if_duplicate=True, ignore_permissions=True)
                frappe.db.commit()
                
                result["inserted"].append(chart["chart_name"])
                print(f"✅ Inserted: {chart['chart_name']}")
            
            except KeyError as e:
                error_msg = f"KeyError for {chart['chart_name']}: {str(e)}"
                result["errors"].append(error_msg)
                frappe.log_error(error_msg, "Dashboard Chart Insert Error")
                print(f"❌ {error_msg}")
            
            except Exception as e:
                error_msg = f"Error inserting {chart['chart_name']}: {str(e)}"
                result["errors"].append(error_msg)
                frappe.log_error(error_msg, "Dashboard Chart Insert Error")
                print(f"❌ {error_msg}")
        
        print(f"\n{'='*60}")
        print(f"Charts Inserted: {len(result['inserted'])}")
        print(f"Charts Skipped: {len(result['skipped'])}")
        print(f"Errors: {len(result['errors'])}")
        print(f"{'='*60}\n")
    
    finally:
        if frappe.db:
            frappe.db.close()
    
    return result


# -----------------------------
# Main Execution
# -----------------------------
def run_all_fixes(site_name: str = None):
    """Run all fixes in sequence"""
    
    print("="*60)
    print("SACCO MANAGEMENT AUTO-FIX SCRIPT")
    print("="*60)
    print()
    
    # Step 1: Fix controllers
    print("[1/3] Fixing DocType controllers...")
    controller_result = fix_controllers()
    
    # Step 2: Fix utilities
    print("\n[2/3] Ensuring utility functions...")
    utils_result = ensure_utility_functions()
    
    # Step 3: Fix dashboard charts
    print("\n[3/3] Inserting dashboard charts...")
    charts_result = insert_dashboard_charts(site_name)
    
    # Summary
    print("\n" + "="*60)
    print("FIX SUMMARY")
    print("="*60)
    print(f"✅ Controllers Created: {len(controller_result['created'])}")
    print(f"🔧 Controllers Fixed: {len(controller_result['fixed'])}")
    print(f"➕ Functions Added: {len(utils_result['added'])}")
    print(f"📊 Charts Inserted: {len(charts_result['inserted'])}")
    print(f"⏭️  Charts Skipped: {len(charts_result['skipped'])}")
    print(f"❌ Total Errors: {len(controller_result['errors']) + len(utils_result['errors']) + len(charts_result['errors'])}")
    print("="*60)
    
    # Next steps
    print("\n📋 NEXT STEPS:")
    print("1. bench --site sitename clear-cache")
    print("2. bench restart")
    print("3. bench --site sitename migrate")
    print()
    
    return {
        "controllers": controller_result,
        "utilities": utils_result,
        "charts": charts_result
    }


if __name__ == "__main__":
    # Get site from command line if provided
    site = None
    if len(sys.argv) > 1:
        site = sys.argv[1]
    
    # Run fixes
    result = run_all_fixes(site)
    
    # Exit with error code if there were errors
    total_errors = (
        len(result["controllers"]["errors"]) +
        len(result["utilities"]["errors"]) +
        len(result["charts"]["errors"])
    )
    
    sys.exit(0 if total_errors == 0 else 1)
